/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/trapanazome.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/trapanazome.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="SpiralPath" />
        <mesh name="trapanazomeBody" geometry={nodes.trapanazomeBody.geometry} material={materials['Material.001']} position={[1.096, -0.622, -0.396]}>
          <mesh name="mitocondria" geometry={nodes.mitocondria.geometry} material={materials.mitocondrea} position={[0.683, 0, -0.291]} rotation={[0, 0.333, 0]} />
          <mesh name="nucleous" geometry={nodes.nucleous.geometry} material={materials.nucleous} position={[2.624, 0, -0.841]} />
        </mesh>
        <mesh name="trapanazomeFin" geometry={nodes.trapanazomeFin.geometry} material={materials.fin} position={[1.096, -0.622, -0.396]} />
      </group>
    </group>
  )
}

useGLTF.preload('/trapanazome.glb')
